/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenInBlack;

import AlienVy.VyAlien;
import AdminVy.VyAdmin;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import AgentVy.VyAgent;

/**
 *
 * @author ifkli
 */
public class InloggningSida extends javax.swing.JFrame {

    private static InfDB idb;
    
    /**
     * Creates new form HuvudFonster
     */
    public InloggningSida(InfDB idb) {
        initComponents();  
        this.idb = idb;
        getRootPane().setDefaultButton(btnAgentInloggning);
        //getRootPane().setDefaultButton(btnAlienInloggning);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgentRubrik = new javax.swing.JLabel();
        lblAgentAnvandarnamn = new javax.swing.JLabel();
        lblAgentLosenord = new javax.swing.JLabel();
        tfAgentAnvandarnamn = new javax.swing.JTextField();
        btnAgentInloggning = new javax.swing.JButton();
        pfAgentLosenord = new javax.swing.JPasswordField();
        btnAlienInloggning = new javax.swing.JButton();
        lblAgentInfo = new javax.swing.JLabel();
        pfAlienLosenord = new javax.swing.JPasswordField();
        tfAlienAnvandarnamn = new javax.swing.JTextField();
        lblAlienRubrik = new javax.swing.JLabel();
        lblAlienAnvandarnamn = new javax.swing.JLabel();
        lblAlienLosenord = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        lblAgentRubrik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAgentRubrik.setText("Agent inloggning");

        lblAgentAnvandarnamn.setText("Användar ID");

        lblAgentLosenord.setText("Lösenord");

        tfAgentAnvandarnamn.setColumns(10);
        tfAgentAnvandarnamn.setPreferredSize(new java.awt.Dimension(90, 20));

        btnAgentInloggning.setText("Logga in");
        btnAgentInloggning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentInloggningActionPerformed(evt);
            }
        });

        pfAgentLosenord.setColumns(10);
        pfAgentLosenord.setPreferredSize(new java.awt.Dimension(90, 20));

        btnAlienInloggning.setText("Logga in");
        btnAlienInloggning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienInloggningActionPerformed(evt);
            }
        });

        pfAlienLosenord.setColumns(10);
        pfAlienLosenord.setPreferredSize(new java.awt.Dimension(90, 20));

        tfAlienAnvandarnamn.setColumns(10);
        tfAlienAnvandarnamn.setPreferredSize(new java.awt.Dimension(90, 20));

        lblAlienRubrik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAlienRubrik.setText("Alien inloggning");

        lblAlienAnvandarnamn.setText("Användar ID");

        lblAlienLosenord.setText("Lösenord");

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MiB.png"))); // NOI18N
        picture.setPreferredSize(new java.awt.Dimension(570, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(picture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAgentAnvandarnamn)
                                            .addComponent(tfAgentAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAgentLosenord)
                                            .addComponent(pfAgentLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblAgentRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgentInloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAlienAnvandarnamn)
                                            .addComponent(tfAlienAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pfAlienLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAlienLosenord)))
                                    .addComponent(btnAlienInloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlienRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(283, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentRubrik)
                    .addComponent(lblAlienRubrik))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAgentAnvandarnamn)
                            .addComponent(lblAgentLosenord))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAgentAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfAgentLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlienAnvandarnamn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAlienLosenord))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAlienAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfAlienLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgentInloggning)
                    .addComponent(btnAlienInloggning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgentInfo)
                .addGap(263, 263, 263))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgentInloggningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentInloggningActionPerformed
        
        if (Validering.tomtTextfalt(tfAgentAnvandarnamn) && Validering.tomtTextfalt(pfAgentLosenord)) {
            if (Validering.kollaHeltal(tfAgentAnvandarnamn)) {
                
                    String anvID = tfAgentAnvandarnamn.getText();
                    String losenord = pfAgentLosenord.getText();
                try {
                    String inloggning = idb.fetchSingle("SELECT losenord FROM AGENT where agent_id=" + anvID);
                        
                        String admin = idb.fetchSingle("select administrator from agent where agent_id =" + anvID);
                        if (admin.equals("J")) {

                            if (losenord.equals(inloggning)) {
                                lblAgentRubrik.setText("Admininloggning");
                                VyAdmin adminVy = new VyAdmin(idb);       
                                adminVy.setVisible(true);
                                dispose();
                            }
                            else{
                                lblAgentRubrik.setText("Fel användarnamn eller lösenord");
                                pfAgentLosenord.setText("");
                            }
                 
                        } else if (losenord.equals(inloggning)) {
                            VyAgent agentVy = new VyAgent(idb);       
                            agentVy.setVisible(true);
                            dispose();
                        } else {
                            lblAgentRubrik.setText("Fel användarnamn eller lösenord");
                            pfAgentLosenord.setText("");
                        }
                    
                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnAgentInloggningActionPerformed

    private void btnAlienInloggningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienInloggningActionPerformed

        if (Validering.tomtTextfalt(tfAlienAnvandarnamn) && Validering.tomtTextfalt(pfAlienLosenord)) {
            if (Validering.kollaHeltal(tfAlienAnvandarnamn)) {

                String anvID = tfAlienAnvandarnamn.getText();
                String losenord = pfAlienLosenord.getText();
                try {
                    String inloggning = idb.fetchSingle("SELECT losenord FROM ALIEN where alien_id=" + anvID);

                    if (losenord.equals(inloggning)) {
                        VyAlien alienVy = new VyAlien(idb);       
                        alienVy.setVisible(true);
                        dispose();
                    } else {
                        lblAlienRubrik.setText("Fel användarnamn eller lösenord");
                        pfAlienLosenord.setText("");
                    }

                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());
                }
            }
        }

    }//GEN-LAST:event_btnAlienInloggningActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InloggningSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InloggningSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InloggningSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InloggningSida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InloggningSida(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgentInloggning;
    private javax.swing.JButton btnAlienInloggning;
    private javax.swing.JLabel lblAgentAnvandarnamn;
    private javax.swing.JLabel lblAgentInfo;
    private javax.swing.JLabel lblAgentLosenord;
    private javax.swing.JLabel lblAgentRubrik;
    private javax.swing.JLabel lblAlienAnvandarnamn;
    private javax.swing.JLabel lblAlienLosenord;
    private javax.swing.JLabel lblAlienRubrik;
    private javax.swing.JPasswordField pfAgentLosenord;
    private javax.swing.JPasswordField pfAlienLosenord;
    private javax.swing.JLabel picture;
    private javax.swing.JTextField tfAgentAnvandarnamn;
    private javax.swing.JTextField tfAlienAnvandarnamn;
    // End of variables declaration//GEN-END:variables
}
