/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlienVy;

import MenInBlack.InloggningSida;
import MenInBlack.Validering;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ifkli
 */
public class VyAlien extends javax.swing.JFrame {

    private static InfDB idb;

    /**
     * Creates new form vyAlien
     */
    public VyAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        tfAnvandarnamn.requestFocus();
        taOmradeschef.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfAnvandarnamn = new javax.swing.JTextField();
        btnBytLosenord = new javax.swing.JButton();
        btnOmradeschef = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taOmradeschef = new javax.swing.JTextArea();
        lblRubrik = new javax.swing.JLabel();
        lblAnvandarnamn = new javax.swing.JLabel();
        lblNuvarande = new javax.swing.JLabel();
        lblNytt = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        pfNuvarande = new javax.swing.JPasswordField();
        pfNytt = new javax.swing.JPasswordField();
        lblRubrik2 = new javax.swing.JLabel();
        lblAnvandarnamn2 = new javax.swing.JLabel();
        tfAnvandarnamn2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        btnBytLosenord.setText("Byt lösenord");
        btnBytLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytLosenordActionPerformed(evt);
            }
        });

        btnOmradeschef.setText("Visa områdeschef");
        btnOmradeschef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmradeschefActionPerformed(evt);
            }
        });

        taOmradeschef.setColumns(20);
        taOmradeschef.setRows(5);
        jScrollPane1.setViewportView(taOmradeschef);

        lblRubrik.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRubrik.setText("Ändra lösenord");

        lblAnvandarnamn.setText("Användar ID");

        lblNuvarande.setText("Nuvarande lösenord");

        lblNytt.setText("Nytt lösenord");

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        lblRubrik2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRubrik2.setText("Visa områdeschef");

        lblAnvandarnamn2.setText("Ditt användar ID");

        tfAnvandarnamn2.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNuvarande)
                            .addComponent(lblNytt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRubrik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBytLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAnvandarnamn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAnvandarnamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfNuvarande)
                            .addComponent(pfNytt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(btnOmradeschef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRubrik2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAnvandarnamn2)
                            .addComponent(tfAnvandarnamn2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRubrik)
                    .addComponent(lblRubrik2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnvandarnamn)
                    .addComponent(lblAnvandarnamn2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAnvandarnamn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOmradeschef)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNuvarande)
                        .addGap(18, 18, 18)
                        .addComponent(pfNuvarande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNytt)
                        .addGap(18, 18, 18)
                        .addComponent(pfNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBytLosenord)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        dispose();
        new InloggningSida(idb).setVisible(true);
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnBytLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytLosenordActionPerformed
        
        
        if (Validering.tomtTextfalt(tfAnvandarnamn) && Validering.tomtTextfalt(pfNuvarande)&& Validering.tomtTextfalt(pfNytt)) {
            if (Validering.kollaHeltal(tfAnvandarnamn)) {

                String anvID = tfAnvandarnamn.getText();
                String nuvarandeLosenord = pfNuvarande.getText();
                String nyttLosenord = pfNytt.getText();
                
                try {
                    String dbLosenord = idb.fetchSingle("SELECT losenord FROM ALIEN where alien_id=" + anvID);

                    if (nuvarandeLosenord.equals(dbLosenord)) {
                        idb.update("update alien set losenord = '" + nyttLosenord + "' where alien_id = " + anvID);
                        JOptionPane.showMessageDialog(null, "Lösenordet är ändrat!");
                        tfAnvandarnamn.setText("");
                        pfNuvarande.setText("");
                        pfNytt.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Nuvarande lösenordet matchar inte!");
                    }

                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());
                }
            }
        
        }
    }//GEN-LAST:event_btnBytLosenordActionPerformed

    private void btnOmradeschefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmradeschefActionPerformed
        if(Validering.kollaHeltal(tfAnvandarnamn2))
        {
        taOmradeschef.setText("");
        String anvID = tfAnvandarnamn2.getText();
        
        ArrayList<HashMap<String, String>> soktInfo;
        
        try {
        String fraga = "select agent.namn, agent.telefon, omrade, benamning from agent, omrade, alien where alien_id = " + anvID + "and agent_id = ansvarig_agent and omrade = omrades_id";
        soktInfo = idb.fetchRows(fraga);
        
        for(HashMap<String, String> omradeschef : soktInfo)
            {   
                taOmradeschef.append("Agentens namn: \n" + omradeschef.get("NAMN") + "\n\n");
                taOmradeschef.append("Telefonnummer: \n" + omradeschef.get("TELEFON") + "\n\n");
                taOmradeschef.append("Område: \n" + omradeschef.get("BENAMNING"));
            }
        }
        catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande " + e.getMessage());
                }
        }
    }//GEN-LAST:event_btnOmradeschefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VyAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VyAlien(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytLosenord;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnOmradeschef;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnvandarnamn;
    private javax.swing.JLabel lblAnvandarnamn2;
    private javax.swing.JLabel lblNuvarande;
    private javax.swing.JLabel lblNytt;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblRubrik2;
    private javax.swing.JPasswordField pfNuvarande;
    private javax.swing.JPasswordField pfNytt;
    private javax.swing.JTextArea taOmradeschef;
    private javax.swing.JTextField tfAnvandarnamn;
    private javax.swing.JTextField tfAnvandarnamn2;
    // End of variables declaration//GEN-END:variables
}
